FROM node:18-alpine as build
WORKDIR /app
COPY frontend/ .
RUN npm install
RUN npm run build
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/ .
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
